name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install OS dependencies
        run: sudo apt-get -y install tmux

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run: python -m pip install poetry==1.3.2

      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true

      - name: Install python dependencies
        run: python -m poetry install

      - name: Code lint
        run: poetry run ruff . --line-length 100

      - name: Run tests
        run: poetry run pytest
